"""Generate sql/01_load.sql from the cleaned CSV files.

Run from the project root:  python3 scripts/build_load_sql.py
The generated SQL is committed, so the database can be built with the
mysql client alone (no Python, no LOAD DATA LOCAL INFILE, no network).
"""
import csv

def lit(v):
    if v == '':
        return 'NULL'
    return "'" + v.replace("\\", "\\\\").replace("'", "''") + "'"

def inserts(table, path, cols):
    rows = list(csv.DictReader(open(path, newline='', encoding='utf-8')))
    out = [f"-- {table}: {len(rows)} rows from {path}",
           f"INSERT INTO {table} ({', '.join(cols)}) VALUES"]
    vals = ["  (" + ", ".join(lit(r[c]) for c in cols) + ")" for r in rows]
    out.append(",\n".join(vals) + ";\n")
    return "\n".join(out)

src_cols = ['source_id', 'publisher', 'title', 'url', 'collection_date', 'raw_file']
# The source register uses access_date; map it to collection_date.
reg = list(csv.DictReader(open('data/source_register.csv', newline='', encoding='utf-8')))
with open('data/clean/source.csv', 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f, lineterminator='\n')
    w.writerow(src_cols)
    for r in reg:
        w.writerow([r['source_id'], r['publisher'], r['title'], r['url'], r['access_date'], r['raw_file']])

parts = [
    "-- 01_load.sql  (GENERATED by scripts/build_load_sql.py -- do not edit by hand)",
    "-- Loads the real snapshot collected 2026-09-30. Run after 00_schema.sql.",
    "USE p1_car_repair;",
    "SET FOREIGN_KEY_CHECKS = 1;",
    "",
    "-- Clear existing rows (child tables first) so a re-run never duplicates data.",
    "DELETE FROM business_service;",
    "DELETE FROM business;",
    "DELETE FROM service;",
    "DELETE FROM service_category;",
    "DELETE FROM source;",
    "",
    inserts('source', 'data/clean/source.csv', src_cols),
    inserts('service_category', 'data/clean/service_category.csv', ['category_id', 'category_name']),
    inserts('service', 'data/clean/service.csv', ['service_id', 'service_name', 'category_id']),
    inserts('business', 'data/clean/business.csv',
            ['business_id', 'business_name', 'street_address', 'city', 'state', 'zip_code',
             'neighborhood', 'website', 'source_id', 'raw_row_ref']),
    inserts('business_service', 'data/clean/business_service.csv',
            ['business_id', 'service_id', 'source_id', 'raw_row_ref', 'observed_wording']),
]
open('sql/01_load.sql', 'w', encoding='utf-8').write("\n".join(parts))
print("wrote sql/01_load.sql")
