-- 01_load.sql  (GENERATED by scripts/build_load_sql.py -- do not edit by hand)
-- Loads the real snapshot collected 2026-09-30. Run after 00_schema.sql.
USE p1_car_repair;
SET FOREIGN_KEY_CHECKS = 1;

-- Clear existing rows (child tables first) so a re-run never duplicates data.
DELETE FROM business_service;
DELETE FROM business;
DELETE FROM service;
DELETE FROM service_category;
DELETE FROM source;

-- source: 21 rows from data/clean/source.csv
INSERT INTO source (source_id, publisher, title, url, collection_date, raw_file) VALUES
  ('SRC01', 'City of Chicago', 'Business Licenses - Current Active (dataset uupf-x98q), Motor Vehicle Services License rows for Lake View, Lincoln Park, Lincoln Square, North Center', 'https://data.cityofchicago.org/Community-Economic-Development/Business-Licenses-Current-Active/uupf-x98q', '2026-09-30', 'data/raw/chicago_business_licenses_2026-09-30.csv'),
  ('SRC02', 'Ashland Tire & Auto', 'Ashland Tire & Auto - General Auto Services (home page)', 'https://www.ashlandtire.com/', '2026-09-30', 'data/raw/snapshots/SRC02.html'),
  ('SRC03', 'Bucaro Brothers Auto Care', 'Bucaro Brothers Auto Care - Full-Service Auto Repair Shop (home page)', 'https://www.bucarobrothersautocare.com/', '2026-09-30', 'data/raw/snapshots/SRC03.html'),
  ('SRC04', 'Cassidy Tire & Service', 'Cassidy Tire - Chicago store page (3235 N Western)', 'https://www.cassidytire.com/stores/view/5163/', '2026-09-30', 'data/raw/snapshots/SRC04.html'),
  ('SRC05', 'Eliot''s Complete Auto Repair', 'Eliot''s Complete Auto Repair - Auto Repair in Chicago IL (home page)', 'https://www.eliotscompleteautorepair.com/', '2026-09-30', 'data/raw/snapshots/SRC05.html'),
  ('SRC06', 'E & J Foreign Cars', 'E & J - Auto Services for you', 'https://www.eandj.com/auto-services', '2026-09-30', 'data/raw/snapshots/SRC06.html'),
  ('SRC07', 'Fred''s Wrigleyville Garage & Auto Repair', 'Fred''s Wrigleyville Garage (home page)', 'http://fredswrigleyvillegarage.com', '2026-09-30', 'data/raw/snapshots/SRC07.html'),
  ('SRC08', 'Lincoln Park Auto Repair Service', 'Lincoln Park Auto Repair Service (home page)', 'https://www.lincolnparkautorepairservice.com/', '2026-09-30', 'data/raw/snapshots/SRC08.html'),
  ('SRC09', 'Mechanista', 'Mechanista (home page)', 'https://mechanista.org/', '2026-09-30', 'data/raw/snapshots/SRC09.html'),
  ('SRC10', 'SimpleTire', 'SimpleTire - Midtown Auto Repair installer listing', 'https://simpletire.com/tire-shops/shop/midtown-auto-repair/93629', '2026-09-30', 'data/raw/snapshots/SRC10.html'),
  ('SRC11', 'North Center Auto Service', 'North Center Auto Service (home page)', 'https://www.northcenterautoservice.com/', '2026-09-30', 'data/raw/snapshots/SRC11.html'),
  ('SRC12', 'Reliable Auto Repair Center', 'Reliable Auto Repair Center Inc (home page)', 'https://www.reliableautorepairchicago.com/', '2026-09-30', 'data/raw/snapshots/SRC12.html'),
  ('SRC13', 'Rockwell Auto Clinic', 'Rockwell Auto Clinic (home page)', 'http://www.rockwellautoclinic.com', '2026-09-30', 'data/raw/snapshots/SRC13.html'),
  ('SRC14', 'Speedline Auto & Tire', 'Speedline Auto & Tire (home page)', 'https://speedlineautotire.com/', '2026-09-30', 'data/raw/snapshots/SRC14.html'),
  ('SRC15', 'Sun Auto Service', 'Sun Auto Service (home page)', 'https://www.sunautoserviceinc.com/', '2026-09-30', 'data/raw/snapshots/SRC15.html'),
  ('SRC16', 'Tuffy Tire & Auto Service (Diversey)', 'Tuffy Chicago - Automotive Maintenance (home page)', 'https://www.tuffychicago.com/', '2026-09-30', 'data/raw/snapshots/SRC16.html'),
  ('SRC17', 'EuroRepairHQ', 'EuroRepairHQ - Autohaus in Chicago Illinois', 'https://eurorepairhq.com/shops/illinois/chicago/autohaus/', '2026-09-30', 'data/raw/snapshots/SRC17.html'),
  ('SRC18', 'Consumers'' Checkbook', 'Ashland Tire & Auto Clinic - Chicago Consumers'' Checkbook', 'https://www.checkbook.org/il/chicago/auto-repair-shops/ashland-tire-and-auto-clinic/lrcz7', '2026-09-30', 'data/raw/snapshots/SRC18.html'),
  ('SRC19', 'Lakeview East Chamber of Commerce', 'Fred''s Wrigleyville Garage & Auto Repair - member listing', 'https://chicago.lakevieweast.com/list/member/fred-s-wrigleyville-garage-auto-repair-3640', '2026-09-30', 'data/raw/snapshots/SRC19.html'),
  ('SRC20', 'North Center Chamber of Commerce', 'Rockwell Auto Clinic - member listing', 'https://business.northcenterchamber.com/list/member/rockwell-auto-clinic-2525', '2026-09-30', 'data/raw/snapshots/SRC20.html'),
  ('SRC21', 'Ravenswood Community Council', 'Mechanista - Ravenswood business directory listing', 'https://business.ravenswoodchicago.org/list/member/mechanista-5610', '2026-09-30', 'data/raw/snapshots/SRC21.html');

-- service_category: 2 rows from data/clean/service_category.csv
INSERT INTO service_category (category_id, category_name) VALUES
  ('1', 'Routine Maintenance'),
  ('2', 'Repair & Diagnostics');

-- service: 7 rows from data/clean/service.csv
INSERT INTO service (service_id, service_name, category_id) VALUES
  ('1', 'Oil Change', '1'),
  ('2', 'Tire Service', '1'),
  ('3', 'Wheel Alignment', '1'),
  ('4', 'Brake Repair', '2'),
  ('5', 'Vehicle Diagnostics', '2'),
  ('6', 'Transmission Repair', '2'),
  ('7', 'A/C & Heating Repair', '2');

-- business: 16 rows from data/clean/business.csv
INSERT INTO business (business_id, business_name, street_address, city, state, zip_code, neighborhood, website, source_id, raw_row_ref) VALUES
  ('1', 'Ashland Tire & Auto Clinic', '3737 N Ashland Ave', 'Chicago', 'IL', '60613', 'Lake View', 'https://www.ashlandtire.com/', 'SRC01', 'LIC:2215290-20250416'),
  ('2', 'Autohaus', '4157 N Lincoln Ave', 'Chicago', 'IL', '60618', 'North Center', NULL, 'SRC01', 'LIC:2522221-20250516'),
  ('3', 'Bucaro Brothers Auto Care', '2707 N Ashland Ave', 'Chicago', 'IL', '60614', 'Lincoln Park', 'https://www.bucarobrothersautocare.com/', 'SRC01', 'LIC:2215128-20250416'),
  ('4', 'Cassidy Tire & Service', '3235 N Western Ave', 'Chicago', 'IL', '60618', 'North Center', 'https://www.cassidytire.com/', 'SRC01', 'LIC:2217572-20241216'),
  ('5', 'E & J Foreign Cars', '4245 N Western Ave', 'Chicago', 'IL', '60618', 'North Center', 'https://www.eandj.com/', 'SRC01', 'LIC:2214364-20250316'),
  ('6', 'Eliot''s Complete Auto Repair', '3658 N Lincoln Ave', 'Chicago', 'IL', '60613', 'North Center', 'https://www.eliotscompleteautorepair.com/', 'SRC01', 'LIC:3069567-20260617'),
  ('7', 'Fred''s Wrigleyville Garage & Auto Repair', '3848 N Clark St', 'Chicago', 'IL', '60613', 'Lake View', 'http://fredswrigleyvillegarage.com/', 'SRC01', 'LIC:2652867-20250416'),
  ('8', 'Lincoln Park Auto Repair Service', '946 W Wrightwood Ave', 'Chicago', 'IL', '60614', 'Lincoln Park', 'https://www.lincolnparkautorepairservice.com/', 'SRC01', 'LIC:2807704-20250916'),
  ('9', 'Mechanista', '4526 N Ravenswood Ave', 'Chicago', 'IL', '60640', 'Lincoln Square', 'https://mechanista.org/', 'SRC01', 'LIC:3030774-20250916'),
  ('10', 'Midtown Auto Repair', '1403 W Shakespeare Ave', 'Chicago', 'IL', '60614', 'Lincoln Park', 'https://www.midtownautorepair.com/', 'SRC01', 'LIC:2278252-20250816'),
  ('11', 'North Center Auto Service', '3455 N Western Ave', 'Chicago', 'IL', '60618', 'North Center', 'https://www.northcenterautoservice.com/', 'SRC01', 'LIC:2541914-20250716'),
  ('12', 'Reliable Auto Repair Center', '3401 N Ashland Ave', 'Chicago', 'IL', '60657', 'Lake View', 'https://www.reliableautorepairchicago.com/', 'SRC01', 'LIC:2213706-20250216'),
  ('13', 'Rockwell Auto Clinic', '4050 N Rockwell St Unit C', 'Chicago', 'IL', '60618', 'North Center', 'http://www.rockwellautoclinic.com/', 'SRC01', 'LIC:2912380-20250716'),
  ('14', 'Speedline Auto & Tire', '5250 N Damen Ave', 'Chicago', 'IL', '60625', 'Lincoln Square', 'https://speedlineautotire.com/', 'SRC01', 'LIC:2279495-20250816'),
  ('15', 'Sun Auto Service', '3201 N Damen Ave', 'Chicago', 'IL', '60618', 'North Center', 'https://www.sunautoserviceinc.com/', 'SRC01', 'LIC:2213900-20241216'),
  ('16', 'Tuffy Tire & Auto Service', '1400 W Diversey Pkwy', 'Chicago', 'IL', '60614', 'Lake View', 'https://www.tuffychicago.com/', 'SRC01', 'LIC:2512022-20250316');

-- business_service: 60 rows from data/clean/business_service.csv
INSERT INTO business_service (business_id, service_id, source_id, raw_row_ref, observed_wording) VALUES
  ('1', '1', 'SRC02', 'OBS:OBS002', 'Oil Changes'),
  ('1', '2', 'SRC02', 'OBS:OBS003', 'Tires and Alignments'),
  ('1', '3', 'SRC02', 'OBS:OBS003', 'Tires and Alignments'),
  ('1', '5', 'SRC02', 'OBS:OBS004', 'engine diagnostics'),
  ('2', '5', 'SRC17', 'OBS:OBS076', 'advanced diagnostic technology specifically designed for European engineering'),
  ('3', '1', 'SRC03', 'OBS:OBS006', 'Fast Oil Change'),
  ('3', '2', 'SRC03', 'OBS:OBS007', 'Tires for Sale'),
  ('3', '3', 'SRC03', 'OBS:OBS008', 'Wheel Alignments'),
  ('3', '4', 'SRC03', 'OBS:OBS009', 'Brake Services'),
  ('3', '5', 'SRC03', 'OBS:OBS010', 'Check Engine Lights'),
  ('3', '6', 'SRC03', 'OBS:OBS011', 'Transmission Services'),
  ('3', '7', 'SRC03', 'OBS:OBS012', 'Car Air Conditioner Repair'),
  ('4', '1', 'SRC04', 'OBS:OBS014', 'Oil Changes'),
  ('4', '2', 'SRC04', 'OBS:OBS015', 'Tire Services'),
  ('4', '4', 'SRC04', 'OBS:OBS016', 'Brakes'),
  ('4', '5', 'SRC04', 'OBS:OBS017', 'Diagnostics'),
  ('5', '4', 'SRC06', 'OBS:OBS027', 'Brake Service and Repairs'),
  ('5', '5', 'SRC06', 'OBS:OBS028', 'Diagnostic Resting'),
  ('5', '6', 'SRC06', 'OBS:OBS029', 'Transmissions services and repairs'),
  ('6', '1', 'SRC05', 'OBS:OBS020', 'Oil Changes'),
  ('6', '3', 'SRC05', 'OBS:OBS021', 'Alignment'),
  ('6', '4', 'SRC05', 'OBS:OBS022', 'Brakes'),
  ('6', '5', 'SRC05', 'OBS:OBS023', 'Diagnostics'),
  ('6', '6', 'SRC05', 'OBS:OBS024', 'Transmission Services'),
  ('6', '7', 'SRC05', 'OBS:OBS025', 'A/C Service'),
  ('7', '1', 'SRC07', 'OBS:OBS031', 'Oil Changes & Fluid Replacement'),
  ('7', '2', 'SRC07', 'OBS:OBS032', 'Tire Mounting, Balancing and Flat Repair'),
  ('7', '3', 'SRC07', 'OBS:OBS033', 'Steering, Suspension & Alignment Repair'),
  ('7', '4', 'SRC07', 'OBS:OBS034', 'Brake Inspections & Repair'),
  ('7', '5', 'SRC07', 'OBS:OBS035', 'Computer, Electrical, & Electronic Systems Diagnosis'),
  ('7', '6', 'SRC07', 'OBS:OBS036', 'Transmissions Service & Repair'),
  ('7', '7', 'SRC07', 'OBS:OBS037', 'Air Conditioning Service & Repair'),
  ('8', '4', 'SRC08', 'OBS:OBS039', 'Brake'),
  ('8', '5', 'SRC08', 'OBS:OBS040', 'Computer Diagnostic'),
  ('8', '6', 'SRC08', 'OBS:OBS041', 'Clutch & Transmission'),
  ('8', '7', 'SRC08', 'OBS:OBS042', 'Heating & AC'),
  ('9', '1', 'SRC09', 'OBS:OBS044', 'Oil change and inspection'),
  ('9', '2', 'SRC09', 'OBS:OBS045', 'Tire Rotation'),
  ('9', '4', 'SRC09', 'OBS:OBS046', 'Brake Pad & Rotor Replacement'),
  ('9', '5', 'SRC09', 'OBS:OBS047', 'Diagnostic Services'),
  ('10', '2', 'SRC10', 'OBS:OBS049', 'Tire installation'),
  ('11', '1', 'SRC11', 'OBS:OBS051', 'Oil Change'),
  ('11', '2', 'SRC11', 'OBS:OBS052', 'Tire Services'),
  ('11', '4', 'SRC11', 'OBS:OBS053', 'Brake Repair'),
  ('11', '5', 'SRC11', 'OBS:OBS054', 'Engine Diagnostics'),
  ('12', '5', 'SRC12', 'OBS:OBS056', 'engine diagnostics'),
  ('13', '2', 'SRC13', 'OBS:OBS058', 'Tires'),
  ('13', '4', 'SRC13', 'OBS:OBS059', 'Brakes'),
  ('13', '5', 'SRC13', 'OBS:OBS060', 'Check Engine Light'),
  ('14', '2', 'SRC14', 'OBS:OBS062', 'Tires'),
  ('14', '4', 'SRC14', 'OBS:OBS063', 'Brake Services'),
  ('14', '7', 'SRC14', 'OBS:OBS064', 'A/C & Heating'),
  ('15', '5', 'SRC15', 'OBS:OBS066', 'Computer Diagnostics'),
  ('15', '6', 'SRC15', 'OBS:OBS067', 'Transmissions'),
  ('15', '7', 'SRC15', 'OBS:OBS068', 'Heating and A/C'),
  ('16', '1', 'SRC16', 'OBS:OBS070', 'Oil Change'),
  ('16', '3', 'SRC16', 'OBS:OBS071', 'Wheel Alignment'),
  ('16', '4', 'SRC16', 'OBS:OBS072', 'Brake Service'),
  ('16', '5', 'SRC16', 'OBS:OBS073', 'Vehicle Diagnostics'),
  ('16', '7', 'SRC16', 'OBS:OBS074', 'A/C Service and Repair');
